builds:
  - binary: bin/deteco
    main: ./cli/deteco/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
     - -X main.Version={{.Version}}
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: kazeburo
    name: deteco
